- name: Documentation Docker
  href: index.yml
- name: Démarrage rapide
  expanded: true
  items:
    - name: Déployer une machine virtuelle Ubuntu avec Docker
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
- name: Didacticiels
  items:
    - name: Application web Python avec Docker et PostgreSQL
      href: ../app-service/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'CI/CD avec Docker, Jenkins et Linux'
      href: /azure/developer/jenkins/pipeline-with-github-and-docker
- name: Guides pratiques
  items:
    - name: Extension de machine virtuelle Docker
      href: 'https://github.com/Azure/azure-docker-extension/blob/master/README.md'
    - name: Machine Docker
      href: ../virtual-machines/linux/docker-machine.md
    - name: Registre de conteneurs Docker
      href: ../container-registry/container-registry-get-started-portal.md
- name: Ressources
  items:
    - name: Feuille de route Azure
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Pilote Docker Azure
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Site Docker Azure
      href: 'https://www.docker.com/docker-azure'
    - name: Site Docker
      href: 'https://docker.com'